
services:
    auth_db:
      image: postgres:10
      ports:
        - "5432:5432"
      env_file:
        - ./auth/.env
      volumes:
        - ./auth_postgres/db:/var/lib/postgresql/data
    
    auth:
      build:
        context: ./auth
        dockerfile: Dockerfile
      entrypoint: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      volumes:
        - ./auth:/server
      depends_on:
        - auth_db
      env_file:
        - ./auth/.env
      ports:
        - "8000:8000"
    
    routes_db:
      image: postgres:10
      ports:
        - "6543:5432"
      env_file:
        - ./routes/.env
      volumes:
        - ./routes_postgres/db:/var/lib/postgresql/data
          
    routes:
      build:
        context: ./routes
        dockerfile: Dockerfile
      entrypoint: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      volumes:
        - ./routes:/server
      depends_on:
        - routes_db
      env_file:
        - ./routes/.env
      ports:
        - "8001:8000"