"""create table route

Revision ID: 5c3a5e03ca73
Revises: 456edf438d02
Create Date: 2022-03-18 17:49:07.675369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c3a5e03ca73'
down_revision = '456edf438d02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes_points',
    sa.Column('point_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['point_id'], ['point.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('point_id', 'route_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routes_points')
    op.drop_table('route')
    # ### end Alembic commands ###
