"""add indexes to point_routes

Revision ID: 5d05bb942551
Revises: a7c9e44d92dd
Create Date: 2022-03-19 19:20:56.993809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d05bb942551'
down_revision = 'a7c9e44d92dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_routes_points_route_id'), 'routes_points', ['route_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routes_points_route_id'), table_name='routes_points')
    # ### end Alembic commands ###
