"""delete field user_id from point

Revision ID: 7ae0d6965c00
Revises: 9260266d067e
Create Date: 2022-03-17 16:09:07.035857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ae0d6965c00'
down_revision = '9260266d067e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes_point', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes_point', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
